package com.lostfound.dao;

import org.mindrot.jbcrypt.BCrypt;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/** Provides database connections and zero-configuration local initialization. */
public final class DBConnection {

    private static final String ENV_URL = System.getenv("DB_URL");
    private static final boolean EMBEDDED = ENV_URL == null || ENV_URL.trim().isEmpty();
    private static final String DB_URL = EMBEDDED ? embeddedUrl() : ENV_URL;
    private static final String DB_USER = envOrDefault("DB_USER", EMBEDDED ? "sa" : "root");
    private static final String DB_PASSWORD = envOrDefault("DB_PASSWORD", EMBEDDED ? "" : "root");

    static {
        try {
            Class.forName(EMBEDDED ? "org.h2.Driver" : "com.mysql.cj.jdbc.Driver");
            if (EMBEDDED) initializeEmbeddedDatabase();
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    private DBConnection() {}

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    public static void close(Connection conn) {
        if (conn != null) {
            try { conn.close(); } catch (SQLException ignored) {}
        }
    }

    private static String embeddedUrl() {
        String configured = System.getenv("LOSTFOUND_DATA_DIR");
        Path dataDir = configured == null || configured.trim().isEmpty()
                ? Paths.get(System.getProperty("user.home"), ".lostfound")
                : Paths.get(configured);
        return "jdbc:h2:file:" + dataDir.resolve("college_lost_found").toAbsolutePath()
                + ";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";
    }

    private static String envOrDefault(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }

    private static void initializeEmbeddedDatabase() throws SQLException {
        try (Connection conn = getConnection(); Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS admins (admin_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, email VARCHAR(100) NOT NULL, full_name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            st.execute("CREATE TABLE IF NOT EXISTS users (user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usn VARCHAR(20) NOT NULL UNIQUE, full_name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, phone VARCHAR(15), department VARCHAR(50), password_hash VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            st.execute("CREATE TABLE IF NOT EXISTS lost_items (item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INT NOT NULL, item_name VARCHAR(100) NOT NULL, category VARCHAR(50) NOT NULL, description TEXT, date_lost DATE NOT NULL, location VARCHAR(200) NOT NULL, image_path VARCHAR(300), contact_info VARCHAR(200) NOT NULL, status VARCHAR(20) DEFAULT 'Active', is_approved BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)");
            st.execute("CREATE TABLE IF NOT EXISTS found_items (item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INT NOT NULL, item_name VARCHAR(100) NOT NULL, category VARCHAR(50) NOT NULL, description TEXT, date_found DATE NOT NULL, location VARCHAR(200) NOT NULL, image_path VARCHAR(300), contact_info VARCHAR(200) NOT NULL, status VARCHAR(20) DEFAULT 'Available', is_approved BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)");
            st.execute("CREATE TABLE IF NOT EXISTS claim_requests (claim_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, found_item_id INT NOT NULL, claimant_user_id INT NOT NULL, proof_description TEXT NOT NULL, status VARCHAR(20) DEFAULT 'Pending', admin_note VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (found_item_id) REFERENCES found_items(item_id) ON DELETE CASCADE, FOREIGN KEY (claimant_user_id) REFERENCES users(user_id) ON DELETE CASCADE, UNIQUE (found_item_id, claimant_user_id))");

            if (isEmpty(st, "admins")) {
                String hash = BCrypt.hashpw("admin@123", BCrypt.gensalt(10));
                st.executeUpdate("INSERT INTO admins (username,password_hash,email,full_name) VALUES ('admin','" + hash + "','admin@college.edu','System Administrator')");
            }
            if (isEmpty(st, "users")) {
                String hash = BCrypt.hashpw("student@123", BCrypt.gensalt(10));
                st.executeUpdate("INSERT INTO users (usn,full_name,email,phone,department,password_hash) VALUES "
                        + "('1RV20CS001','Arjun Sharma','arjun.sharma@student.edu','9876543210','Computer Science','" + hash + "'),"
                        + "('1RV20EC045','Priya Patel','priya.patel@student.edu','9845123456','Electronics','" + hash + "'),"
                        + "('1RV20ME012','Rahul Nair','rahul.nair@student.edu','9901234567','Mechanical','" + hash + "')");
            }
            if (isEmpty(st, "lost_items")) {
                st.executeUpdate("INSERT INTO lost_items (user_id,item_name,category,description,date_lost,location,contact_info,status) VALUES (1,'Blue Water Bottle','Accessories','Steel blue water bottle with my name engraved','2024-01-15','Cafeteria','9876543210','Active'),(2,'Scientific Calculator','Electronics','Casio FX-991ES Plus','2024-01-18','Lab Block 2, Room 204','9845123456','Active')");
            }
            if (isEmpty(st, "found_items")) {
                st.executeUpdate("INSERT INTO found_items (user_id,item_name,category,description,date_found,location,contact_info,status) VALUES (2,'Black Wallet','Accessories','Black leather wallet with student ID inside','2024-01-16','Parking Lot Block A','9845123456','Available'),(3,'Umbrella','Accessories','Purple umbrella','2024-01-19','Main Entrance','9901234567','Available')");
            }
        }
    }

    private static boolean isEmpty(Statement st, String table) throws SQLException {
        try (ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM " + table)) {
            return rs.next() && rs.getInt(1) == 0;
        }
    }
}
